Add PercentageValidator and tests
afucher/Inquirer pull request #14
Opened 2020-10-01 19:47 UTC by Reisclef

2020-10-04 01:04 UTC, afucher commented
Hey @Reisclef thanks for your PR! 🎉 

One thing that I was expecting in a Percentage validator is that the user should be able to input with the percentage symbol, like "50%".

2020-10-04 01:10 UTC, afucher requested changes
Thanks for your PR.

2020-10-04 01:10 UTC, afucher commented on test/InquirerUnitTest/Validators/PercentageValidatorUnitTest.cs
> +            validator.GetErrorMessage().Should().Be("Sorry, a percentage must be a number between 0 and 100");
We don't need to add "Sorry,"at the error message.

2020-10-04 01:10 UTC, afucher commented on test/InquirerUnitTest/Validators/PercentageValidatorUnitTest.cs
> +        public void ShouldAcceptValuesBetween0And100(string aPercentValue)
Values with the percentage symbol should be valid, like 50%

2020-10-04 13:02 UTC, Reisclef commented
Okay, cool. I wasn't sure whether that would be the case, and I didn't want to assume. Have a look at the newest commit and let me know if anything else needs changing.

2020-10-05 01:49 UTC, afucher requested changes
Thanks for the changes, I just found some corner cases.

2020-10-05 01:49 UTC, afucher commented on src/Inquirer/Validators/PercentageValidator.cs
> +                var numberWithoutPercent = value.Replace("%", "");
Reading the code I think that values like "75%%", "7%5" or "%75" will be valid, could you check this? 
Those values that I mentioned could be added to the tests data.

2020-10-05 15:13 UTC, Reisclef commented
Alright, sure thing. Additional unit tests done. Also added an extra expected fail test for another symbol, in this case a dollar symbol.

2020-10-05 16:25 UTC, afucher commented
Hey @Reisclef, sorry, I think that I didn't express myself clear. Those values that I mentioned, are supposed to fail.

Like, "75" and "75%" are a valid percentage value, but "7%5" and "75%%" are not.

2020-10-05 16:35 UTC, Reisclef commented
Ah, I did wonder why that would be considered valid! Okay, so only a percentage at the end is valid. I'll look into making the appropriate changes.

2020-10-05 21:30 UTC, Reisclef commented
New commit pushed with additional tests validating various inputs. Let me know if you have any further comments.

2020-10-05 22:31 UTC, afucher approved these changes
Nice, thanks for your contribution!

2020-10-05 22:31 UTC, merged